---
- name: 외부 SSL 인증서 수동 등록 (Hardcoded)
  hosts: bastion
  become: no

  tasks:
    # =================================================================
    # 예로써 (www.miso.com)
    # =================================================================
    - name: "[www] 1. 인증서(crt) 파일 Bastion 복사"
      ansible.builtin.copy:
        src: "./www_miso_com.crt"  # 앤서블 실행 위치의 원본 파일
        dest: "/tmp/www_miso_com.crt"    # Bastion의 임시 경로
        mode: "0600"

    - name: "[www] 2. 개인키(key) 파일 Bastion 복사"
      ansible.builtin.copy:
        src: "./www_miso_com.key"
        dest: "/tmp/www_miso_com.key"
        mode: "0600"

    - name: "[www] 3. K8s Secret (miso-com-tls) 생성 및 덮어쓰기" #시크릿이름 주의
      ansible.builtin.shell: |
        kubectl create secret tls miso-com-tls \ 
          --cert=/tmp/www_miso_com.crt \
          --key=/tmp/www_miso_com.key \
          -n default \
          --dry-run=client -o yaml | kubectl apply -f -
      register: www_secret
      changed_when: "'created' in www_secret.stdout or 'configured' in www_secret.stdout"

    - name: "[www] 4. 보안을 위해 Bastion 임시 파일 삭제"
      ansible.builtin.shell: rm -f /tmp/www_miso_com.crt /tmp/www_miso_com.key


    # =================================================================
    # 템플릿 복붙해서 사용하면 됨.
    # =================================================================
    # - name: "[api] 1. 인증서(crt) 파일 Bastion 복사"
    #   ansible.builtin.copy:
    #     src: "./files/api_miso_com.crt"
    #     dest: "/tmp/api_miso_com.crt"
    #     mode: "0600"
    # 
    # - name: "[api] 2. 개인키(key) 파일 Bastion 복사"
    #   ansible.builtin.copy:
    #     src: "./files/api_miso_com.key"
    #     dest: "/tmp/api_miso_com.key"
    #     mode: "0600"
    # 
    # - name: "[api] 3. K8s Secret (miso-api-tls) 생성 및 덮어쓰기"
    #   ansible.builtin.shell: |
    #     kubectl create secret tls miso-api-tls \
    #       --cert=/tmp/api_miso_com.crt \
    #       --key=/tmp/api_miso_com.key \
    #       -n default \
    #       --dry-run=client -o yaml | kubectl apply -f -
    # 
    # - name: "[api] 4. 보안을 위해 Bastion 임시 파일 삭제"
    #   ansible.builtin.shell: rm -f /tmp/api_miso_com.crt /tmp/api_miso_com.key